config:
  default: true
  MD013: false        # Line length - disabled for docs
  MD033: false        # Inline HTML - needed for Svelte components
  MD041: false        # First line h1 - frontmatter handles this
  MD024:
    siblings_only: true  # Allow duplicate headings in different sections

globs:
  - "docs/**/*.md"
  - "curriculum/**/*.md"

ignores:
  - "**/node_modules/**"
  - "site/build/**"
  - "SCAFFOLD-REPORT.md"
  - "SPRINT_PLAN.md"
